#!/usr/bin/env bash


tmux_dir=~/.dotfiles/tmux_secs
vim_dir=~/.dotfiles/vim_secs


case $1 in
    vim)
        sec_dir=$vim_dir
    ;;

    tmux)
        sec_dir=$tmux_dir
    ;;
esac


if [[ $1 ]]; then
    cd $sec_dir
    sec_file=$(fzf --border sharp --margin 2% --padding 5% --info inline --prompt 'SEARCH: ' --pointer '**' --ansi --color 'bg+:-1,pointer:green,fg+:green,hl:yellow,border:blue' | cut -d. -f1)

    if [[ $sec_file ]]; then
        case $sec_dir in
            $tmux_dir)
                tmuxinator $sec_file
            ;;

            $vim_dir)
                nvim -S $sec_file
            ;;
        esac
    fi
fi


